// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class TestResult {
    /**
     * Creates a new TestResult instance.
     * @param {Partial<TestResult>} [$$source = {}] - The source object to create the TestResult.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("passed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["passed"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestResult(/** @type {Partial<TestResult>} */($$parsedSource));
    }
}
