// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Auth describes how to authenticate a request. The resolved credential is
 * applied as a header (query placement comes later). Fields support {{vars}}.
 */
export class Auth {
    /**
     * Creates a new Auth instance.
     * @param {Partial<Auth>} [$$source = {}] - The source object to create the Auth.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "none" | "bearer" | "basic" | "apikey"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("token" in $$source)) {
            /**
             * bearer
             * @member
             * @type {string}
             */
            this["token"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * basic
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * basic
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("key" in $$source)) {
            /**
             * apikey: header name
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * apikey: header value
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Auth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Auth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Auth(/** @type {Partial<Auth>} */($$parsedSource));
    }
}

/**
 * Cookie is a flattened view of a stored cookie for the UI.
 */
export class Cookie {
    /**
     * Creates a new Cookie instance.
     * @param {Partial<Cookie>} [$$source = {}] - The source object to create the Cookie.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Cookie instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Cookie}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Cookie(/** @type {Partial<Cookie>} */($$parsedSource));
    }
}

/**
 * FormField is one row of a urlencoded or multipart form body. For Type=="file"
 * Value is a local filesystem path that gets streamed into a multipart part.
 */
export class FormField {
    /**
     * Creates a new FormField instance.
     * @param {Partial<FormField>} [$$source = {}] - The source object to create the FormField.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "text" | "file"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormField instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FormField}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FormField(/** @type {Partial<FormField>} */($$parsedSource));
    }
}

/**
 * Header is an ordered, toggleable key/value pair (Postman-style). The same
 * shape is used for both request and response headers so the frontend editor
 * and viewer can share a component.
 */
export class Header {
    /**
     * Creates a new Header instance.
     * @param {Partial<Header>} [$$source = {}] - The source object to create the Header.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Header instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Header}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Header(/** @type {Partial<Header>} */($$parsedSource));
    }
}

/**
 * Request is the protocol-agnostic input to an executor. Only "http" is
 * implemented today; the Protocol field reserves room for graphql/ws/grpc,
 * which slot in behind the same Execute entry point later.
 * 
 * Per-request execution options use inverted boolean names so the zero value
 * keeps the safe defaults (follow redirects, verify TLS, no timeout).
 */
export class Request {
    /**
     * Creates a new Request instance.
     * @param {Partial<Request>} [$$source = {}] - The source object to create the Request.
     */
    constructor($$source = {}) {
        if (!("protocol" in $$source)) {
            /**
             * "" or "http" for now
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {Header[]}
             */
            this["headers"] = [];
        }
        if (!("body" in $$source)) {
            /**
             * raw/json bodies
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("bodyType" in $$source)) {
            /**
             * "none" | "raw" | "json" | "urlencoded" | "formdata"
             * @member
             * @type {string}
             */
            this["bodyType"] = "";
        }
        if (!("formFields" in $$source)) {
            /**
             * @member
             * @type {FormField[]}
             */
            this["formFields"] = [];
        }
        if (!("auth" in $$source)) {
            /**
             * @member
             * @type {Auth | null}
             */
            this["auth"] = null;
        }
        if (!("variables" in $$source)) {
            /**
             * resolved environment vars for {{interpolation}}
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["variables"] = {};
        }
        if (!("timeoutMs" in $$source)) {
            /**
             * 0 = no timeout
             * @member
             * @type {number}
             */
            this["timeoutMs"] = 0;
        }
        if (!("disableRedirect" in $$source)) {
            /**
             * false = follow redirects
             * @member
             * @type {boolean}
             */
            this["disableRedirect"] = false;
        }
        if (!("maxRedirects" in $$source)) {
            /**
             * 0 = stdlib default (10)
             * @member
             * @type {number}
             */
            this["maxRedirects"] = 0;
        }
        if (!("insecureSkipVerify" in $$source)) {
            /**
             * false = verify TLS
             * @member
             * @type {boolean}
             */
            this["insecureSkipVerify"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Request instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Request}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField6_0 = $$createType3;
        const $$createField7_0 = $$createType5;
        const $$createField8_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        if ("formFields" in $$parsedSource) {
            $$parsedSource["formFields"] = $$createField6_0($$parsedSource["formFields"]);
        }
        if ("auth" in $$parsedSource) {
            $$parsedSource["auth"] = $$createField7_0($$parsedSource["auth"]);
        }
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField8_0($$parsedSource["variables"]);
        }
        return new Request(/** @type {Partial<Request>} */($$parsedSource));
    }
}

/**
 * Response is what the UI renders: status, headers, body and timing/size.
 */
export class Response {
    /**
     * Creates a new Response instance.
     * @param {Partial<Response>} [$$source = {}] - The source object to create the Response.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("statusText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusText"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {Header[]}
             */
            this["headers"] = [];
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("timing" in $$source)) {
            /**
             * @member
             * @type {Timing}
             */
            this["timing"] = (new Timing());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Response instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Response}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField2_0($$parsedSource["headers"]);
        }
        if ("timing" in $$parsedSource) {
            $$parsedSource["timing"] = $$createField5_0($$parsedSource["timing"]);
        }
        return new Response(/** @type {Partial<Response>} */($$parsedSource));
    }
}

/**
 * Timing is the per-phase breakdown captured via net/http/httptrace, in
 * milliseconds. Zero means the phase did not occur (e.g. TLS on plain HTTP, or
 * a reused keep-alive connection that skipped DNS/connect).
 */
export class Timing {
    /**
     * Creates a new Timing instance.
     * @param {Partial<Timing>} [$$source = {}] - The source object to create the Timing.
     */
    constructor($$source = {}) {
        if (!("dnsMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dnsMs"] = 0;
        }
        if (!("connectMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["connectMs"] = 0;
        }
        if (!("tlsMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tlsMs"] = 0;
        }
        if (!("ttfbMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ttfbMs"] = 0;
        }
        if (!("totalMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Timing instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Timing}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Timing(/** @type {Partial<Timing>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Header.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = FormField.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Auth.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = Timing.createFrom;
