// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RequestDetail {
    /**
     * Creates a new RequestDetail instance.
     * @param {Partial<RequestDetail>} [$$source = {}] - The source object to create the RequestDetail.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["headers"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("preScript" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preScript"] = "";
        }
        if (!("postScript" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["postScript"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("bodyType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bodyType"] = "";
        }
        if (!("formFields" in $$source)) {
            /**
             * JSON array
             * @member
             * @type {string}
             */
            this["formFields"] = "";
        }
        if (!("graphqlVars" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["graphqlVars"] = "";
        }
        if (!("grpcMethod" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["grpcMethod"] = "";
        }
        if (!("auth" in $$source)) {
            /**
             * JSON object
             * @member
             * @type {string}
             */
            this["auth"] = "";
        }
        if (!("settings" in $$source)) {
            /**
             * JSON object: per-request execution settings
             * @member
             * @type {string}
             */
            this["settings"] = "";
        }
        if (!("examples" in $$source)) {
            /**
             * JSON array of saved request+response snapshots
             * @member
             * @type {string}
             */
            this["examples"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RequestDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RequestDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RequestDetail(/** @type {Partial<RequestDetail>} */($$parsedSource));
    }
}

export class TreeNode {
    /**
     * Creates a new TreeNode instance.
     * @param {Partial<TreeNode>} [$$source = {}] - The source object to create the TreeNode.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentId"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("sortOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }
        if (!("hasChildren" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasChildren"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TreeNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TreeNode}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TreeNode(/** @type {Partial<TreeNode>} */($$parsedSource));
    }
}
