// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as index$0 from "./internal/index/models.js";

/**
 * CreateFolder adds a new folder under parentID (empty == root).
 * @param {string} parentID
 * @param {string} name
 * @returns {$CancellablePromise<index$0.TreeNode>}
 */
export function CreateFolder(parentID, name) {
    return $Call.ByID(1447735573, parentID, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateRequest adds a new empty request under parentID (empty == root).
 * @param {string} parentID
 * @param {string} name
 * @param {string} method
 * @returns {$CancellablePromise<index$0.TreeNode>}
 */
export function CreateRequest(parentID, name, method) {
    return $Call.ByID(1976736442, parentID, name, method).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteNode removes a node and all of its descendants.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNode(id) {
    return $Call.ByID(3510978374, id);
}

/**
 * DuplicateNode creates a deep copy of a request or folder (including all
 * descendants) as the next sibling of the original.
 * @param {string} id
 * @returns {$CancellablePromise<index$0.TreeNode>}
 */
export function DuplicateNode(id) {
    return $Call.ByID(3846844226, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ExportCollection renders the whole index as a Postman v2.1 JSON document.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ExportCollection(name) {
    return $Call.ByID(637473995, name);
}

/**
 * ExportCollectionToFile writes the Postman v2.1 export to path. Reliable from
 * the webview (the browser download path does not work in WKWebView).
 * @param {string} path
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function ExportCollectionToFile(path, name) {
    return $Call.ByID(3621961792, path, name);
}

/**
 * GetChildren returns the direct children of a folder node.
 * @param {string} parentID
 * @returns {$CancellablePromise<index$0.TreeNode[]>}
 */
export function GetChildren(parentID) {
    return $Call.ByID(1552572656, parentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetRequestDetail loads body/headers/scripts for a request from SQLite.
 * This is the ONLY place heavy content is read — not during tree rendering.
 * @param {string} id
 * @returns {$CancellablePromise<index$0.RequestDetail | null>}
 */
export function GetRequestDetail(id) {
    return $Call.ByID(193531561, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetRootItems returns the top-level nodes in the collection tree.
 * @returns {$CancellablePromise<index$0.TreeNode[]>}
 */
export function GetRootItems() {
    return $Call.ByID(47490365).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ImportCollection parses collection.json into the SQLite index.
 * Skips re-parse if the file mtime is unchanged.
 * Returns immediately; emits "collection:ready" or "collection:error" when done.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function ImportCollection(path) {
    return $Call.ByID(3423304824, path);
}

/**
 * ListRequestsUnder returns the requests at/below a node in run order. Used by
 * the Collection Runner.
 * @param {string} id
 * @returns {$CancellablePromise<index$0.TreeNode[]>}
 */
export function ListRequestsUnder(id) {
    return $Call.ByID(874310379, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * MoveNode re-parents a node and sets its position among siblings (0-based).
 * Used by the sidebar drag-and-drop. Moving into self or a descendant returns
 * an error.
 * @param {string} id
 * @param {string} newParentID
 * @param {number} newIndex
 * @returns {$CancellablePromise<void>}
 */
export function MoveNode(id, newParentID, newIndex) {
    return $Call.ByID(835779216, id, newParentID, newIndex);
}

/**
 * PickExport opens a native save-file dialog and writes the Postman export to
 * the chosen path. Returns the path ("" if cancelled).
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function PickExport(name) {
    return $Call.ByID(2956308126, name);
}

/**
 * PickImport opens a native open-file dialog and imports the chosen collection.
 * Returns the selected path ("" if the user cancelled). Import runs async and
 * emits the usual collection:* events.
 * @returns {$CancellablePromise<string>}
 */
export function PickImport() {
    return $Call.ByID(1387098213);
}

/**
 * PickImportOpenAPI opens a native dialog, parses an OpenAPI 3 / Swagger 2 spec
 * and MERGES it into the current collection (under a folder named after the
 * spec). Returns the selected path ("" if cancelled).
 * @returns {$CancellablePromise<string>}
 */
export function PickImportOpenAPI() {
    return $Call.ByID(4109996867);
}

/**
 * RenameNode changes a node's display name.
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RenameNode(id, name) {
    return $Call.ByID(2713596163, id, name);
}

/**
 * SaveRequest persists edits to an existing request into the index.
 * @param {index$0.RequestDetail} d
 * @returns {$CancellablePromise<void>}
 */
export function SaveRequest(d) {
    return $Call.ByID(4021096921, d);
}

/**
 * Search runs FTS5 full-text search and returns matching nodes.
 * @param {string} query
 * @returns {$CancellablePromise<index$0.TreeNode[]>}
 */
export function Search(query) {
    return $Call.ByID(1217559273, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = index$0.TreeNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = index$0.RequestDetail.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
