// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as index$0 from "./internal/index/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspaces$0 from "./internal/workspaces/models.js";

/**
 * ActiveWorkspaceID returns the currently active workspace id.
 * @returns {$CancellablePromise<string>}
 */
export function ActiveWorkspaceID() {
    return $Call.ByID(572508857);
}

/**
 * AncestorContexts returns the folder-context JSON for each ancestor of id,
 * root-to-immediate-parent order. The frontend merges these at send time
 * (child overrides parent).
 * @param {string} id
 * @returns {$CancellablePromise<string[]>}
 */
export function AncestorContexts(id) {
    return $Call.ByID(3330305184, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ClearAll removes every item from the collection index.
 * @returns {$CancellablePromise<void>}
 */
export function ClearAll() {
    return $Call.ByID(73446265);
}

/**
 * CreateFolder adds a new folder under parentID (empty == root).
 * @param {string} parentID
 * @param {string} name
 * @returns {$CancellablePromise<index$0.TreeNode>}
 */
export function CreateFolder(parentID, name) {
    return $Call.ByID(1447735573, parentID, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateRequest adds a new empty request under parentID (empty == root).
 * @param {string} parentID
 * @param {string} name
 * @param {string} method
 * @returns {$CancellablePromise<index$0.TreeNode>}
 */
export function CreateRequest(parentID, name, method) {
    return $Call.ByID(1976736442, parentID, name, method).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateWorkspace adds a new workspace and returns it. Doesn't switch to it —
 * the frontend usually wants to confirm + then SwitchWorkspace.
 * @param {string} name
 * @returns {$CancellablePromise<workspaces$0.Workspace>}
 */
export function CreateWorkspace(name) {
    return $Call.ByID(2924801694, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * DeleteNode removes a node and all of its descendants.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNode(id) {
    return $Call.ByID(3510978374, id);
}

/**
 * DeleteWorkspace removes a workspace AND its DB file. Refuses to delete the
 * last remaining one.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteWorkspace(id) {
    return $Call.ByID(913569755, id);
}

/**
 * DuplicateNode creates a deep copy of a request or folder (including all
 * descendants) as the next sibling of the original.
 * @param {string} id
 * @returns {$CancellablePromise<index$0.TreeNode>}
 */
export function DuplicateNode(id) {
    return $Call.ByID(3846844226, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExportCollection renders the whole index as a Postman v2.1 JSON document.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ExportCollection(name) {
    return $Call.ByID(637473995, name);
}

/**
 * ExportCollectionToFile writes the Postman v2.1 export to path. Reliable from
 * the webview (the browser download path does not work in WKWebView).
 * @param {string} path
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function ExportCollectionToFile(path, name) {
    return $Call.ByID(3621961792, path, name);
}

/**
 * GetChildren returns the direct children of a folder node.
 * @param {string} parentID
 * @returns {$CancellablePromise<index$0.TreeNode[]>}
 */
export function GetChildren(parentID) {
    return $Call.ByID(1552572656, parentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetFolderContext loads the folder's inheritance JSON blob (shared headers /
 * auth / scripts). Returns "{}" if empty.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function GetFolderContext(id) {
    return $Call.ByID(2781383114, id);
}

/**
 * GetRequestDetail loads body/headers/scripts for a request from SQLite.
 * This is the ONLY place heavy content is read — not during tree rendering.
 * @param {string} id
 * @returns {$CancellablePromise<index$0.RequestDetail | null>}
 */
export function GetRequestDetail(id) {
    return $Call.ByID(193531561, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetRootItems returns the top-level nodes in the collection tree.
 * @returns {$CancellablePromise<index$0.TreeNode[]>}
 */
export function GetRootItems() {
    return $Call.ByID(47490365).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ImportAllFromPostman fetches every collection and environment from the
 * Postman API using the given API key, then imports them all.
 * Collections are fetched in parallel (up to 8 concurrent requests); SQLite
 * writes are serialised. Environments are fetched in parallel afterward.
 * @param {string} apiKey
 * @returns {$CancellablePromise<void>}
 */
export function ImportAllFromPostman(apiKey) {
    return $Call.ByID(4127778447, apiKey);
}

/**
 * ImportCollection parses collection.json into the SQLite index.
 * Skips re-parse if the file mtime is unchanged.
 * Returns immediately; emits "collection:ready" or "collection:error" when done.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function ImportCollection(path) {
    return $Call.ByID(3423304824, path);
}

/**
 * ImportFromURL fetches a URL and imports it as a Postman collection or
 * OpenAPI/Swagger spec. It auto-detects the format from the content.
 * The import is asynchronous; it emits the usual collection:* events.
 * Supported URL types:
 *   - Any direct JSON/YAML URL (GitHub raw, gist, etc.)
 *   - Postman public share links (getpostman.com/collections/…)
 *   - Postman API URLs with ?access_key=… or X-Api-Key header
 * @param {string} rawURL
 * @returns {$CancellablePromise<void>}
 */
export function ImportFromURL(rawURL) {
    return $Call.ByID(1088323765, rawURL);
}

/**
 * ImportHARBytes merges a HAR JSON document (typically pasted from browser
 * DevTools' "Save all as HAR") into the current collection. Each entry becomes
 * a request under a new HAR-tagged folder. Returns the number of imported
 * requests, or an error if the JSON is not valid HAR.
 * @param {string} data
 * @returns {$CancellablePromise<number>}
 */
export function ImportHARBytes(data) {
    return $Call.ByID(3510927218, data);
}

/**
 * ListRequestsUnder returns the requests at/below a node in run order. Used by
 * the Collection Runner.
 * @param {string} id
 * @returns {$CancellablePromise<index$0.TreeNode[]>}
 */
export function ListRequestsUnder(id) {
    return $Call.ByID(874310379, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListWorkspaces returns all known workspaces.
 * @returns {$CancellablePromise<workspaces$0.Workspace[]>}
 */
export function ListWorkspaces() {
    return $Call.ByID(2927415971).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * MoveNode re-parents a node and sets its position among siblings (0-based).
 * Used by the sidebar drag-and-drop. Moving into self or a descendant returns
 * an error.
 * @param {string} id
 * @param {string} newParentID
 * @param {number} newIndex
 * @returns {$CancellablePromise<void>}
 */
export function MoveNode(id, newParentID, newIndex) {
    return $Call.ByID(835779216, id, newParentID, newIndex);
}

/**
 * PickExport opens a native save-file dialog and writes the Postman export to
 * the chosen path. Returns the path ("" if cancelled).
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function PickExport(name) {
    return $Call.ByID(2956308126, name);
}

/**
 * PickImport opens a native open-file dialog and imports the chosen collection.
 * Returns the selected path ("" if the user cancelled). Import runs async and
 * emits the usual collection:* events.
 * @returns {$CancellablePromise<string>}
 */
export function PickImport() {
    return $Call.ByID(1387098213);
}

/**
 * PickImportOpenAPI opens a native dialog, parses an OpenAPI 3 / Swagger 2 spec
 * and MERGES it into the current collection (under a folder named after the
 * spec). Returns the selected path ("" if cancelled).
 * @returns {$CancellablePromise<string>}
 */
export function PickImportOpenAPI() {
    return $Call.ByID(4109996867);
}

/**
 * RenameNode changes a node's display name.
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RenameNode(id, name) {
    return $Call.ByID(2713596163, id, name);
}

/**
 * RenameWorkspace updates the display name.
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RenameWorkspace(id, name) {
    return $Call.ByID(4077716920, id, name);
}

/**
 * SaveRequest persists edits to an existing request into the index.
 * @param {index$0.RequestDetail} d
 * @returns {$CancellablePromise<void>}
 */
export function SaveRequest(d) {
    return $Call.ByID(4021096921, d);
}

/**
 * Search runs FTS5 full-text search and returns matching nodes.
 * @param {string} query
 * @returns {$CancellablePromise<index$0.TreeNode[]>}
 */
export function Search(query) {
    return $Call.ByID(1217559273, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SetFolderContext persists the folder's inheritance JSON blob.
 * @param {string} id
 * @param {string} contextJSON
 * @returns {$CancellablePromise<void>}
 */
export function SetFolderContext(id, contextJSON) {
    return $Call.ByID(4227757102, id, contextJSON);
}

/**
 * SwitchWorkspace tears down the current index, opens the requested
 * workspace's DB, and emits collection:ready so the frontend reloads the
 * tree. Concurrent calls are serialized.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SwitchWorkspace(id) {
    return $Call.ByID(1305933266, id);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = index$0.TreeNode.createFrom;
const $$createType2 = workspaces$0.Workspace.createFrom;
const $$createType3 = $Create.Array($$createType1);
const $$createType4 = index$0.RequestDetail.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType2);
