// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EnvService exposes environment persistence to the frontend. The frontend owns
 * editing; this just loads/saves the whole document.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as envstore$0 from "./internal/envstore/models.js";

/**
 * LoadEnvironments returns the persisted environments + active selection.
 * @returns {$CancellablePromise<envstore$0.State>}
 */
export function LoadEnvironments() {
    return $Call.ByID(3654828536).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SaveEnvironments persists the whole environment document.
 * @param {envstore$0.State} state
 * @returns {$CancellablePromise<void>}
 */
export function SaveEnvironments(state) {
    return $Call.ByID(2639754853, state);
}

// Private type creation functions
const $$createType0 = envstore$0.State.createFrom;
