// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExecService is the Wails service that runs requests. Kept separate from
 * CollectionService so request execution and the collection index stay
 * decoupled as more protocols (graphql/ws/grpc) are added.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as httpclient$0 from "./internal/httpclient/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as script$0 from "./internal/script/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel aborts an in-flight request started with the given reqId.
 * @param {string} reqId
 * @returns {$CancellablePromise<void>}
 */
export function Cancel(reqId) {
    return $Call.ByID(3079587158, reqId);
}

/**
 * ClearCookies empties the session cookie jar.
 * @returns {$CancellablePromise<void>}
 */
export function ClearCookies() {
    return $Call.ByID(150933912);
}

/**
 * DeleteCookie removes a cookie by name within the URL's scope.
 * @param {string} url
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCookie(url, name) {
    return $Call.ByID(2879512561, url, name);
}

/**
 * GetCookies returns the cookies the session jar would send to url.
 * @param {string} url
 * @returns {$CancellablePromise<httpclient$0.Cookie[]>}
 */
export function GetCookies(url) {
    return $Call.ByID(313924767, url).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SendRequest runs the optional pre-request script, executes the request, then
 * runs the optional test script. reqId lets the UI cancel via Cancel. reqName
 * is the request's display name — used as the key for
 * `{{Name.response.body.path}}` chaining references.
 * @param {string} reqId
 * @param {string} reqName
 * @param {httpclient$0.Request} req
 * @param {string} preScript
 * @param {string} postScript
 * @returns {$CancellablePromise<$models.SendResult | null>}
 */
export function SendRequest(reqId, reqName, req, preScript, postScript) {
    return $Call.ByID(1404814375, reqId, reqName, req, preScript, postScript).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SetCookie adds or overwrites a cookie for the URL.
 * @param {string} url
 * @param {string} name
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetCookie(url, name, value) {
    return $Call.ByID(229750378, url, name, value);
}

/**
 * TryPreScript runs a pre-request script in isolation (no HTTP send) so the
 * user can iterate on the script editor without burning real requests. Vars
 * are echoed back as the script's mutation result; logs surface in the UI's
 * test results panel.
 * @param {string} src
 * @param {{ [_ in string]?: string }} vars
 * @returns {$CancellablePromise<script$0.Result>}
 */
export function TryPreScript(src, vars) {
    return $Call.ByID(403487005, src, vars).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * TryTestScript runs a test script against a frontend-provided response
 * snapshot (typically the tab's last `response`). Returns the assertions +
 * any console output. No HTTP fired.
 * @param {string} src
 * @param {{ [_ in string]?: string }} vars
 * @param {script$0.ScriptResponse} resp
 * @returns {$CancellablePromise<script$0.Result>}
 */
export function TryTestScript(src, vars, resp) {
    return $Call.ByID(1622208978, src, vars, resp).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = httpclient$0.Cookie.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SendResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = script$0.Result.createFrom;
