// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExecService is the Wails service that runs requests. Kept separate from
 * CollectionService so request execution and the collection index stay
 * decoupled as more protocols (graphql/ws/grpc) are added.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as httpclient$0 from "./internal/httpclient/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel aborts an in-flight request started with the given reqId.
 * @param {string} reqId
 * @returns {$CancellablePromise<void>}
 */
export function Cancel(reqId) {
    return $Call.ByID(3079587158, reqId);
}

/**
 * ClearCookies empties the session cookie jar.
 * @returns {$CancellablePromise<void>}
 */
export function ClearCookies() {
    return $Call.ByID(150933912);
}

/**
 * GetCookies returns the cookies the session jar would send to url.
 * @param {string} url
 * @returns {$CancellablePromise<httpclient$0.Cookie[]>}
 */
export function GetCookies(url) {
    return $Call.ByID(313924767, url).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SendRequest runs the optional pre-request script, executes the request, then
 * runs the optional test script. reqId lets the UI cancel via Cancel.
 * @param {string} reqId
 * @param {httpclient$0.Request} req
 * @param {string} preScript
 * @param {string} postScript
 * @returns {$CancellablePromise<$models.SendResult | null>}
 */
export function SendRequest(reqId, req, preScript, postScript) {
    return $Call.ByID(1404814375, reqId, req, preScript, postScript).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = httpclient$0.Cookie.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SendResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
