// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GRPCService makes dynamic unary gRPC calls using server reflection — no .proto
 * files needed, like grpcurl. Plaintext only for now (TLS comes later).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Call invokes a unary method. fullMethod is "pkg.Service/Method"; reqJSON is the
 * request message as JSON. Returns the response message as JSON.
 * @param {string} target
 * @param {string} fullMethod
 * @param {string} reqJSON
 * @returns {$CancellablePromise<$models.GRPCResult | null>}
 */
export function Call(target, fullMethod, reqJSON) {
    return $Call.ByID(3789372009, target, fullMethod, reqJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListMethods returns fully-qualified method names ("pkg.Service/Method")
 * exposed by the server, via reflection.
 * @param {string} target
 * @returns {$CancellablePromise<string[]>}
 */
export function ListMethods(target) {
    return $Call.ByID(1165480405, target).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.GRPCResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
