// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GRPCService makes dynamic gRPC calls (unary + streaming) using server
 * reflection — no .proto files needed, like grpcurl.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Call invokes a unary method. fullMethod is "pkg.Service/Method"; reqJSON is the
 * request message as JSON. Returns the response message as JSON.
 * @param {string} target
 * @param {string} fullMethod
 * @param {string} reqJSON
 * @returns {$CancellablePromise<$models.GRPCResult | null>}
 */
export function Call(target, fullMethod, reqJSON) {
    return $Call.ByID(3789372009, target, fullMethod, reqJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListMethods returns fully-qualified method names ("pkg.Service/Method")
 * exposed by the server, via reflection.
 * @param {string} target
 * @returns {$CancellablePromise<string[]>}
 */
export function ListMethods(target) {
    return $Call.ByID(1165480405, target).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * StreamCall opens a server-streaming (or client/bidi) RPC. Frames arrive on
 * the `grpc:event` Wails event; for client-side streams, call StreamSend to
 * push messages. StreamClose ends the call.
 * @param {string} streamID
 * @param {string} target
 * @param {string} fullMethod
 * @param {string} reqJSON
 * @returns {$CancellablePromise<void>}
 */
export function StreamCall(streamID, target, fullMethod, reqJSON) {
    return $Call.ByID(3699269353, streamID, target, fullMethod, reqJSON);
}

/**
 * StreamCancel hard-cancels a running stream.
 * @param {string} streamID
 * @returns {$CancellablePromise<void>}
 */
export function StreamCancel(streamID) {
    return $Call.ByID(1688622683, streamID);
}

/**
 * StreamCloseSend signals end-of-input on a client/bidi stream.
 * @param {string} streamID
 * @returns {$CancellablePromise<void>}
 */
export function StreamCloseSend(streamID) {
    return $Call.ByID(4232710933, streamID);
}

/**
 * StreamSend pushes a JSON message into a client/bidi stream.
 * @param {string} streamID
 * @param {string} msgJSON
 * @returns {$CancellablePromise<void>}
 */
export function StreamSend(streamID, msgJSON) {
    return $Call.ByID(2982211311, streamID, msgJSON);
}

// Private type creation functions
const $$createType0 = $models.GRPCResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
