// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as httpclient$0 from "./internal/httpclient/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as script$0 from "./internal/script/models.js";

/**
 * GRPCResult is the response of a unary call.
 */
export class GRPCResult {
    /**
     * Creates a new GRPCResult instance.
     * @param {Partial<GRPCResult>} [$$source = {}] - The source object to create the GRPCResult.
     */
    constructor($$source = {}) {
        if (!("body" in $$source)) {
            /**
             * response message as JSON
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * RPC/error message, if any
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GRPCResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GRPCResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GRPCResult(/** @type {Partial<GRPCResult>} */($$parsedSource));
    }
}

/**
 * GitStatus is a coarse report on a working tree.
 */
export class GitStatus {
    /**
     * Creates a new GitStatus instance.
     * @param {Partial<GitStatus>} [$$source = {}] - The source object to create the GitStatus.
     */
    constructor($$source = {}) {
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * `git status --porcelain` (empty = clean)
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("hasRepo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasRepo"] = false;
        }
        if (!("remote" in $$source)) {
            /**
             * Remote tracking — empty when the local branch has no upstream
             * configured (e.g. fresh `git init` with no remote yet).
             * @member
             * @type {string}
             */
            this["remote"] = "";
        }
        if (!("upstream" in $$source)) {
            /**
             * e.g. "origin/master"
             * @member
             * @type {string}
             */
            this["upstream"] = "";
        }
        if (!("ahead" in $$source)) {
            /**
             * commits to push
             * @member
             * @type {number}
             */
            this["ahead"] = 0;
        }
        if (!("behind" in $$source)) {
            /**
             * commits to pull
             * @member
             * @type {number}
             */
            this["behind"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitStatus(/** @type {Partial<GitStatus>} */($$parsedSource));
    }
}

/**
 * MockStatus reports the running mock server's port and last error, if any.
 */
export class MockStatus {
    /**
     * Creates a new MockStatus instance.
     * @param {Partial<MockStatus>} [$$source = {}] - The source object to create the MockStatus.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MockStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MockStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MockStatus(/** @type {Partial<MockStatus>} */($$parsedSource));
    }
}

/**
 * SendResult bundles the response with script side-effects so the UI can show
 * test results and persist any variable changes a script made.
 */
export class SendResult {
    /**
     * Creates a new SendResult instance.
     * @param {Partial<SendResult>} [$$source = {}] - The source object to create the SendResult.
     */
    constructor($$source = {}) {
        if (!("response" in $$source)) {
            /**
             * @member
             * @type {httpclient$0.Response | null}
             */
            this["response"] = null;
        }
        if (!("tests" in $$source)) {
            /**
             * @member
             * @type {script$0.TestResult[]}
             */
            this["tests"] = [];
        }
        if (!("logs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["logs"] = [];
        }
        if (!("vars" in $$source)) {
            /**
             * variable map after pre/post scripts
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["vars"] = {};
        }
        if (!("scriptError" in $$source)) {
            /**
             * non-fatal: a script threw
             * @member
             * @type {string}
             */
            this["scriptError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SendResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("response" in $$parsedSource) {
            $$parsedSource["response"] = $$createField0_0($$parsedSource["response"]);
        }
        if ("tests" in $$parsedSource) {
            $$parsedSource["tests"] = $$createField1_0($$parsedSource["tests"]);
        }
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField2_0($$parsedSource["logs"]);
        }
        if ("vars" in $$parsedSource) {
            $$parsedSource["vars"] = $$createField3_0($$parsedSource["vars"]);
        }
        return new SendResult(/** @type {Partial<SendResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = httpclient$0.Response.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = script$0.TestResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
