// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService exposes the self-update flow to the frontend. Two-step on
 * purpose: Check returns metadata so the UI can show release notes + a confirm
 * button before Apply touches the binary.
 * 
 * The download URLs are kept server-side (cached in lastInfo) so they never
 * need to round-trip through the frontend — Apply() uses the cached result.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "./internal/update/models.js";

/**
 * ApplyUpdate downloads and installs the cached update. On success the running
 * binary has been replaced; the caller should prompt for restart.
 * @returns {$CancellablePromise<void>}
 */
export function ApplyUpdate() {
    return $Call.ByID(3973249877);
}

/**
 * CheckForUpdate queries the latest GitHub release and reports whether a newer
 * version is available for this platform. The result is cached so ApplyUpdate
 * can use the original Info (including internal download URLs).
 * @returns {$CancellablePromise<update$0.Info | null>}
 */
export function CheckForUpdate() {
    return $Call.ByID(654227894).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CurrentVersion returns the build-injected Version string ("dev" in unstamped
 * local builds). Used by the Settings panel header.
 * @returns {$CancellablePromise<string>}
 */
export function CurrentVersion() {
    return $Call.ByID(212359031);
}

/**
 * RepoSlug returns the owner/repo the updater queries. Exposed for the UI's
 * "view releases" link.
 * @returns {$CancellablePromise<string>}
 */
export function RepoSlug() {
    return $Call.ByID(3512118079);
}

// Private type creation functions
const $$createType0 = update$0.Info.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
