// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WSService manages live WebSocket connections. Each connection is identified by
 * a frontend-supplied connId; messages and state changes are pushed to the UI
 * as "ws:event" Wails events carrying that connId.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as httpclient$0 from "./internal/httpclient/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close terminates a connection.
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function Close(connID) {
    return $Call.ByID(1345206881, connID);
}

/**
 * Connect dials url and starts pumping incoming frames as events. Variables are
 * interpolated into the URL and header values by the caller already; headers
 * here are sent as-is.
 * @param {string} connID
 * @param {string} url
 * @param {httpclient$0.Header[]} headers
 * @returns {$CancellablePromise<void>}
 */
export function Connect(connID, url, headers) {
    return $Call.ByID(1293801903, connID, url, headers);
}

/**
 * Send writes a text frame on the named connection.
 * @param {string} connID
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function Send(connID, data) {
    return $Call.ByID(382304349, connID, data);
}

/**
 * @param {$models.EventEmitter} e
 * @returns {$CancellablePromise<void>}
 */
export function SetEmitter(e) {
    return $Call.ByID(89951633, e);
}
